<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\EventStore.TestClient\EventStore.TestClient.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\EventStore.Common\Utils\version.properties">
			<Link>version.properties</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
