<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<OutputType>Exe</OutputType>
		<GenerateSupportedRuntime>false</GenerateSupportedRuntime>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="EventStore.Client.Grpc.Streams" />
		<PackageReference Include="EventStore.Client.Grpc.Operations" />
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.CommandLine.DragonFruit" />
		<PackageReference Include="TrogonEventStore.Plugins" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\EventStore.Common\EventStore.Common.csproj" />
		<ProjectReference Include="..\EventStore.Core\EventStore.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\EventStore.ClusterNode\logconfig.json">
			<Link>logconfig.json</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\EventStore.Common\Utils\version.properties">
			<Link>version.properties</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
