<Project>
	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<DebugType Condition=" '$(Configuration)' == 'Debug' ">full</DebugType>
		<DebugType Condition=" '$(Configuration)' == 'Release' ">pdbonly</DebugType>
		<Authors>Straw Hat, LLC</Authors>
		<Company>Straw Hat, LLC</Company>
		<PackageIcon>trogon-logo.png</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/TrogonStack/TrogonEventStore</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Copyright>Copyright 2011-2024, Event Store Ltd; Copyright 2025-2026, Straw Hat, LLC</Copyright>
		<PackageReleaseNotes>https://github.com/TrogonStack/TrogonEventStore/releases</PackageReleaseNotes>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/TrogonStack/TrogonEventStore</RepositoryUrl>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<Platforms>AnyCPU;x64;ARM64</Platforms>
		<IsPackable>false</IsPackable>
		<VersionPrefix>0.0.3</VersionPrefix>
		<VersionSuffix/>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE.md" Pack="true" PackagePath="\"/>
		<None Include="..\..\NOTICE.html" Pack="true" PackagePath="\"/>
		<None Include="..\..\trogon-logo.png" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
