name: Build Alpine Container

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - main
      - release/v*
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

jobs:
  build-container-alpine:
    uses: ./.github/workflows/build-container-reusable.yml
    with:
      container-runtime: alpine
