name: Build Container - Reusable

on:
  workflow_call:
    inputs:
      container-runtime:
        required: true
        type: string
      runtime:
        required: true
        type: string

jobs:
  build-container:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ inputs.container-runtime }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install net8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: eventstore
          build-args: |
            CONTAINER_RUNTIME=${{ inputs.container-runtime }}
            RUNTIME=${{ inputs.runtime }}
      - name: Verify Build
        run: |
          docker run --rm eventstore --insecure --what-if
      - name: Build Test Container
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          target: test
          tags: eventstore-test
          build-args: |
            CONTAINER_RUNTIME=${{ inputs.container-runtime }}
            RUNTIME=${{ inputs.runtime }}
      - name: Run Tests
        run: |
          docker run \
          --volume $(pwd)/test-results:/build/test-results \
          --rm \
          eventstore-test
      - name: Publish Test Results (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: test-results/test-results.html
          name: test-results-${{ inputs.container-runtime }}.html
      - name: Publish Test Results (All)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ inputs.container-runtime }}
          path: test-results
