name: Debian LTS Container

on:
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-container-reusable.yml
    with:
      container-runtime: bookworm-slim
      runtime: linux-x64
    secrets: inherit
