name: Ubuntu LTS Container

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - release/v*
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-images:
    name: Build Images
    uses: ./.github/workflows/build-container-reusable.yml
    with:
      container-runtime: noble
      runtime: linux-x64
      mode: build-only
      test-image-artifact-name: eventstore-test-image-noble-linux-x64
    secrets: inherit

  test:
    name: Build (${{ matrix.test-group-name }})
    needs: build-images
    strategy:
      fail-fast: true
      matrix:
        include:
          - test-group-name: core-clientapi
          - test-group-name: core-http
          - test-group-name: core-services
          - test-group-name: core-cluster-services
          - test-group-name: core-storage
          - test-group-name: core-hash-collisions
          - test-group-name: core-transforms
          - test-group-name: core-rest
          - test-group-name: core-xunit
          - test-group-name: projections
          - test-group-name: misc
    uses: ./.github/workflows/build-container-reusable.yml
    with:
      container-runtime: noble
      runtime: linux-x64
      mode: test-only
      test-image-artifact-name: eventstore-test-image-noble-linux-x64
      test-group-name: ${{ matrix.test-group-name }}
    secrets: inherit
