name: Ubuntu LTS ARM64

on:
  pull_request:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - release/v*
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: ubuntu-24.04-arm
      arch: arm64
    secrets: inherit

  required:
    name: ARM64 CI
    if: ${{ always() }}
    needs:
      - build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Require successful jobs
        env:
          REQUIRED_JOBS: ${{ toJSON(needs) }}
        run: jq -e 'all(.[]; .result == "success")' <<< "$REQUIRED_JOBS"
