name: Ubuntu LTS X64

on:
  push:
    branches:
      - master
      - release/v*
    tags:
      - v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: ubuntu-24.04
      arch: x64
    secrets: inherit
