name: Ubuntu LTS ARM64

on:
  pull_request:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - release/v*
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Changes
    uses: ./.github/workflows/changes-reusable.yml

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    name: Build
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: ubuntu-24.04-arm
      arch: arm64
    secrets: inherit

  required:
    name: ARM64 CI
    if: ${{ always() }}
    needs:
      - changes
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install task runner
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.2
          install: false
          cache: false
      - name: Require successful jobs
        env:
          REQUIRED_JOBS: ${{ toJSON(needs) }}
        run: mise run --skip-tools github:actions:require-successful-jobs
