name: Build Ubuntu 24.04 X64

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: ubuntu-24.04
      arch: x64
