name: Common

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - main
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: Scan for Vulnerabilities
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install net8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - name: Scan for Vulnerabilities
        run: |
          cd src
          dotnet restore --locked-mode
          dotnet list package --vulnerable --include-transitive | tee vulnerabilities.txt
          ! cat vulnerabilities.txt | grep -q "has the following vulnerable packages"
  protolock:
    runs-on: ubuntu-latest
    name: Protolock Status
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Protolock Status
        shell: bash
        run: |
          ./protolock.sh status --uptodate
  docker-compose:
    runs-on: ubuntu-latest
    name: Docker Compose Smoke Test
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Registry Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Compose Smoke Test
        run: |
          docker compose build
          docker compose up --detach
          printf 'Waiting for cluster'
          timeout 60 bash -c -- 'until $(curl --output /dev/null --silent --insecure --fail https://localhost:2113/health/live); do printf '.'; sleep 2; done'
          docker compose down
