name: Common

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"
  push:
    branches:
      - master
      - main
      - release/oss-v*
    tags:
      - oss-v*
    paths-ignore:
      - "docs/**"
      - "samples/**"
      - "**.md"

permissions:
  contents: read
  packages: read

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: Scan for Vulnerabilities
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install net8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Set up .NET NuGet authentication
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/TrogonStack/index.json" \
            --name "github" \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text
      - name: Scan for Vulnerabilities
        run: |
          cd src
          dotnet restore
          dotnet list package --vulnerable --include-transitive | tee vulnerabilities.txt
          ! cat vulnerabilities.txt | grep -q "has the following vulnerable packages"

  protolock:
    runs-on: ubuntu-latest
    name: Protolock Status
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Protolock Status
        shell: bash
        run: |
          ./protolock.sh status --uptodate
  docker-compose:
    runs-on: ubuntu-latest
    name: Docker Compose Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Registry Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Compose Smoke Test
        env:
          DOCKER_BUILDKIT: 1
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker compose build
          docker compose up --detach
          printf 'Waiting for cluster'
          timeout 60 bash -c -- 'until $(curl --output /dev/null --silent --insecure --fail https://localhost:2113/health/live); do printf '.'; sleep 2; done'
          docker compose down
