name: Publish Container Image

on:
  workflow_call:
    inputs:
      image-artifact-name:
        required: true
        type: string

jobs:
  publish-container-image:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install task runner
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.8.2
          install: false
          cache: false
      - name: Download Container
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.image-artifact-name }}
      - name: Load Container
        run: mise run --skip-tools github-actions:container -- load-runtime
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Container
        env:
          IMAGE: ghcr.io/trogonstack/trogoneventstore
        run: mise run --skip-tools github-actions:publish-container
